version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      go-deps:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(docker)"
