run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - misspell
  settings:
    goimports:
      local-prefixes: github.com/wys1203/keda-deprecation-webhook
